# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'traceWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import UI.resources_rc

class Ui_TraceWindow(object):
    def setupUi(self, TraceWindow):
        if not TraceWindow.objectName():
            TraceWindow.setObjectName(u"TraceWindow")
        TraceWindow.resize(1400, 1000)
        icon = QIcon()
        icon.addFile(u":/mainWindow/logo_no_bg.png", QSize(), QIcon.Normal, QIcon.Off)
        TraceWindow.setWindowIcon(icon)
        TraceWindow.setStyleSheet(u"background-color: rgb(220, 240, 189);\n"
"font:  \"Ubuntu Mono\";")
        self.action16_bit = QAction(TraceWindow)
        self.action16_bit.setObjectName(u"action16_bit")
        self.action32_bit = QAction(TraceWindow)
        self.action32_bit.setObjectName(u"action32_bit")
        self.action64_bit = QAction(TraceWindow)
        self.action64_bit.setObjectName(u"action64_bit")
        self.actionfull_address = QAction(TraceWindow)
        self.actionfull_address.setObjectName(u"actionfull_address")
        self.action_3 = QAction(TraceWindow)
        self.action_3.setObjectName(u"action_3")
        self.action16_bit_2 = QAction(TraceWindow)
        self.action16_bit_2.setObjectName(u"action16_bit_2")
        self.actionabsolute = QAction(TraceWindow)
        self.actionabsolute.setObjectName(u"actionabsolute")
        self.actionrelative_address = QAction(TraceWindow)
        self.actionrelative_address.setObjectName(u"actionrelative_address")
        self.centralwidget = QWidget(TraceWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(10, 0, 1341, 911))
        self.splitter.setOrientation(Qt.Horizontal)
        self.verticalLayoutWidget = QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.code_area = QVBoxLayout(self.verticalLayoutWidget)
        self.code_area.setObjectName(u"code_area")
        self.code_area.setContentsMargins(0, 0, 0, 0)
        self.func_combo = QComboBox(self.verticalLayoutWidget)
        self.func_combo.setObjectName(u"func_combo")

        self.code_area.addWidget(self.func_combo)

        self.func_stack = QStackedWidget(self.verticalLayoutWidget)
        self.func_stack.setObjectName(u"func_stack")
        self.func_stack.setStyleSheet(u"\\\\background-color: rgb(252, 242, 162);\n"
"background-color: rgb(255, 255, 255);")

        self.code_area.addWidget(self.func_stack)

        self.splitter.addWidget(self.verticalLayoutWidget)
        self.widget_2 = QWidget(self.splitter)
        self.widget_2.setObjectName(u"widget_2")
        self.stack_frame = QListView(self.widget_2)
        self.stack_frame.setObjectName(u"stack_frame")
        self.stack_frame.setGeometry(QRect(270, 450, 221, 241))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack_frame.sizePolicy().hasHeightForWidth())
        self.stack_frame.setSizePolicy(sizePolicy)
        self.calling_stack = QListWidget(self.widget_2)
        self.calling_stack.setObjectName(u"calling_stack")
        self.calling_stack.setGeometry(QRect(10, 450, 211, 241))
        sizePolicy.setHeightForWidth(self.calling_stack.sizePolicy().hasHeightForWidth())
        self.calling_stack.setSizePolicy(sizePolicy)
        self.calling_stack.setMinimumSize(QSize(0, 0))
        self.calling_stack.setMaximumSize(QSize(300, 16777215))
        self.calling_stack.setStyleSheet(u"")
        self.calling_stack.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.calling_stack.setSelectionMode(QAbstractItemView.NoSelection)
        self.calling_stack.setProperty("isWrapping", False)
        self.widget = QWidget(self.widget_2)
        self.widget.setObjectName(u"widget")
        self.widget.setEnabled(True)
        self.widget.setGeometry(QRect(10, 20, 701, 131))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.cont_btn = QPushButton(self.widget)
        self.cont_btn.setObjectName(u"cont_btn")
        self.cont_btn.setGeometry(QRect(20, 0, 116, 100))
        self.cont_btn.setMinimumSize(QSize(0, 100))
        font = QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cont_btn.setFont(font)
        self.cont_btn.setFlat(False)
        self.step_btn = QPushButton(self.widget)
        self.step_btn.setObjectName(u"step_btn")
        self.step_btn.setGeometry(QRect(150, 0, 100, 100))
        self.step_btn.setMinimumSize(QSize(100, 100))
        self.step_btn.setFont(font)
        self.step_btn.setToolTipDuration(1)
        self.step_btn.setStyleSheet(u"border-image: url(:/traceWindow/step_in.png);")
        self.step_out_btn = QPushButton(self.widget)
        self.step_out_btn.setObjectName(u"step_out_btn")
        self.step_out_btn.setGeometry(QRect(270, 0, 100, 100))
        self.step_out_btn.setMinimumSize(QSize(100, 100))
        self.step_out_btn.setFont(font)
        self.step_out_btn.setStyleSheet(u"border-image: url(:/traceWindow/step_out.png);")
        self.step_over_btn = QPushButton(self.widget)
        self.step_over_btn.setObjectName(u"step_over_btn")
        self.step_over_btn.setGeometry(QRect(390, 0, 100, 100))
        self.step_over_btn.setMinimumSize(QSize(100, 100))
        self.step_over_btn.setMaximumSize(QSize(300, 300))
        self.step_over_btn.setSizeIncrement(QSize(1, 1))
        self.step_over_btn.setFont(font)
#if QT_CONFIG(tooltip)
        self.step_over_btn.setToolTip(u"<html><head/><body><p>step over</p></body></html>")
#endif // QT_CONFIG(tooltip)
        self.step_over_btn.setAutoFillBackground(False)
        self.step_over_btn.setStyleSheet(u"border-image: url(:/traceWindow/step_over.png);")
        self.back_instruction = QPushButton(self.widget)
        self.back_instruction.setObjectName(u"back_instruction")
        self.back_instruction.setGeometry(QRect(510, 0, 116, 100))
        self.back_instruction.setMinimumSize(QSize(0, 100))
        self.back_instruction.setFont(font)
        self.back_instruction.setFlat(False)
        self.registers_view = QTableView(self.widget_2)
        self.registers_view.setObjectName(u"registers_view")
        self.registers_view.setGeometry(QRect(10, 170, 701, 271))
        self.registers_view.setMaximumSize(QSize(800, 400))
        font1 = QFont()
        font1.setFamily(u"Ubuntu Mono")
        font1.setBold(False)
        font1.setItalic(False)
        font1.setWeight(50)
        self.registers_view.setFont(font1)
        self.registers_view.setLayoutDirection(Qt.LeftToRight)
        self.registers_view.setShowGrid(False)
        self.registers_view.setGridStyle(Qt.NoPen)
        self.frame = QFrame(self.widget_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(50, 730, 551, 161))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 51, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setWeight(50)
        self.label.setFont(font2)
        self.num_bytes_line_edit = QLineEdit(self.frame)
        self.num_bytes_line_edit.setObjectName(u"num_bytes_line_edit")
        self.num_bytes_line_edit.setGeometry(QRect(80, 20, 91, 25))
        self.num_bytes_line_edit.setFont(font1)
        self.num_bytes_line_edit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 10, 181, 41))
        self.label_2.setFont(font2)
        self.address_line_edit = QLineEdit(self.frame)
        self.address_line_edit.setObjectName(u"address_line_edit")
        self.address_line_edit.setGeometry(QRect(360, 20, 161, 25))
        self.address_line_edit.setFont(font1)
        self.address_line_edit.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.data_area = QTextEdit(self.frame)
        self.data_area.setObjectName(u"data_area")
        self.data_area.setGeometry(QRect(160, 60, 361, 91))
        self.data_area.setFont(font1)
        self.data_area.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.data_area.setReadOnly(True)
        self.get_data_btn = QPushButton(self.frame)
        self.get_data_btn.setObjectName(u"get_data_btn")
        self.get_data_btn.setGeometry(QRect(10, 90, 121, 41))
        self.splitter.addWidget(self.widget_2)
        TraceWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(TraceWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1400, 22))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(238, 238, 236, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(246, 246, 245, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(119, 119, 118, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(159, 159, 157, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        self.menuBar.setPalette(palette)
        self.menuview = QMenu(self.menuBar)
        self.menuview.setObjectName(u"menuview")
        self.menuaddress = QMenu(self.menuview)
        self.menuaddress.setObjectName(u"menuaddress")
        TraceWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuview.menuAction())
        self.menuview.addSeparator()
        self.menuview.addAction(self.menuaddress.menuAction())
        self.menuaddress.addSeparator()
        self.menuaddress.addAction(self.actionabsolute)
        self.menuaddress.addAction(self.actionrelative_address)

        self.retranslateUi(TraceWindow)

        self.func_stack.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(TraceWindow)
    # setupUi

    def retranslateUi(self, TraceWindow):
        TraceWindow.setWindowTitle(QCoreApplication.translate("TraceWindow", u"ASMtracer", None))
        self.action16_bit.setText(QCoreApplication.translate("TraceWindow", u"16-bit", None))
        self.action32_bit.setText(QCoreApplication.translate("TraceWindow", u"32-bit", None))
        self.action64_bit.setText(QCoreApplication.translate("TraceWindow", u"64-bit", None))
        self.actionfull_address.setText(QCoreApplication.translate("TraceWindow", u"full address", None))
        self.action_3.setText(QCoreApplication.translate("TraceWindow", u"address", None))
        self.action16_bit_2.setText(QCoreApplication.translate("TraceWindow", u"16-bit", None))
        self.actionabsolute.setText(QCoreApplication.translate("TraceWindow", u"absolute address", None))
        self.actionrelative_address.setText(QCoreApplication.translate("TraceWindow", u"relative address", None))
        self.cont_btn.setText(QCoreApplication.translate("TraceWindow", u"continue", None))
#if QT_CONFIG(tooltip)
        self.step_btn.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.step_btn.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.step_btn.setText("")
        self.step_out_btn.setText("")
        self.step_over_btn.setText("")
        self.back_instruction.setText(QCoreApplication.translate("TraceWindow", u"current", None))
        self.label.setText(QCoreApplication.translate("TraceWindow", u"read", None))
        self.label_2.setText(QCoreApplication.translate("TraceWindow", u"bytes from address", None))
        self.get_data_btn.setText(QCoreApplication.translate("TraceWindow", u"get data", None))
        self.menuview.setTitle(QCoreApplication.translate("TraceWindow", u"view", None))
        self.menuaddress.setTitle(QCoreApplication.translate("TraceWindow", u"address", None))
    # retranslateUi

